# Generated by Django 5.0 on 2023-12-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('B', 'Berries'), ('F', 'Fruits'), ('I', 'Insects'), ('S', 'Seeds')], default='B', max_length=1),
        ),
    ]
