# Generated by Django 5.0 on 2024-01-03 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_feeding_options_feeding_finch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
